// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Traily.AgentTeam.Persistence;

#nullable disable

namespace Traily.AgentTeam.Persistence.Migrations
{
    [DbContext(typeof(TrailyDbContext))]
    [Migration("20261005132046_AddYouTrackProviderConfiguration")]
    partial class AddYouTrackProviderConfiguration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("Traily.AgentTeam.Agents.AgentExternalIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("SourceId", "ExternalUserId")
                        .IsUnique();

                    b.HasIndex("SourceId", "Login");

                    b.ToTable("AgentExternalIdentities", (string)null);
                });

            modelBuilder.Entity("Traily.AgentTeam.Agents.AgentProfile", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletionRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxConcurrentJobs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeletionRequestedAt");

                    b.ToTable("AgentProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_AgentProfiles_MaxConcurrentJobs", "\"MaxConcurrentJobs\" > 0");
                        });
                });

            modelBuilder.Entity("Traily.AgentTeam.Agents.AgentSkill", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "SkillId")
                        .IsUnique();

                    b.ToTable("AgentSkills", (string)null);
                });

            modelBuilder.Entity("Traily.AgentTeam.Git.AgentRepositoryAccess", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepositoryId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("AgentId", "RepositoryId");

                    b.HasIndex("RepositoryId");

                    b.ToTable("AgentRepositoryAccesses", (string)null);
                });

            modelBuilder.Entity("Traily.AgentTeam.Git.GitRepository", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPathOverride")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SourceId");

                    b.ToTable("GitRepositories", (string)null);
                });

            modelBuilder.Entity("Traily.AgentTeam.Git.ManagedProject", b =>
                {
                    b.Property<string>("SourceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalProjectId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkSourceConnectionId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("SourceId");

                    b.HasIndex("WorkSourceConnectionId");

                    b.ToTable("ManagedProjects", null, t =>
                        {
                            t.HasCheckConstraint("CK_ManagedProjects_ExternalProjectId", "length(trim(\"ExternalProjectId\")) > 0");

                            t.HasCheckConstraint("CK_ManagedProjects_WorkSourceConnectionId", "length(trim(\"WorkSourceConnectionId\")) > 0");
                        });
                });

            modelBuilder.Entity("Traily.AgentTeam.Integrations.YouTrack.YouTrackConnectionConfiguration", b =>
                {
                    b.Property<string>("ConnectionId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtectedAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ConnectionId");

                    b.ToTable("YouTrackConnectionConfigurations");
                });

            modelBuilder.Entity("Traily.AgentTeam.Integrations.YouTrack.YouTrackProjectConfiguration", b =>
                {
                    b.Property<string>("SourceId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("AssigneeField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscoveryQueryTemplate")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkflowStateField")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SourceId");

                    b.ToTable("YouTrackProjectConfigurations");
                });

            modelBuilder.Entity("Traily.AgentTeam.Operations.OperationalIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Availability")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Capability")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("FirstObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<long>("ObservationCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ScopeType", "ScopeId", "Capability")
                        .IsUnique()
                        .HasFilter("\"ResolvedAt\" IS NULL");

                    b.ToTable("OperationalIssues", (string)null);
                });

            modelBuilder.Entity("Traily.AgentTeam.WorkItems.WorkItemExecutionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phase")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PlanningCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanningInputJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanningResultJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderSessionId")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("StopReason")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskSnapshot")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("TaskSourceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkItemJobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkingDirectory")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WorkItemJobId");

                    b.ToTable("WorkItemExecutionAttempts", (string)null);
                });

            modelBuilder.Entity("Traily.AgentTeam.WorkItems.WorkItemJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CurrentAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAssigneeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalWorkItemId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SourceUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkItemReference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "Status");

                    b.HasIndex("SourceId", "ExternalWorkItemId")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("WorkItemJobs", (string)null);
                });

            modelBuilder.Entity("Traily.AgentTeam.WorkSources.WorkSourceConnection", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WorkSourceConnections", (string)null);
                });

            modelBuilder.Entity("Traily.AgentTeam.Agents.AgentExternalIdentity", b =>
                {
                    b.HasOne("Traily.AgentTeam.Agents.AgentProfile", "Agent")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Traily.AgentTeam.Agents.AgentSkill", b =>
                {
                    b.HasOne("Traily.AgentTeam.Agents.AgentProfile", "Agent")
                        .WithMany("Skills")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Traily.AgentTeam.Git.AgentRepositoryAccess", b =>
                {
                    b.HasOne("Traily.AgentTeam.Agents.AgentProfile", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Traily.AgentTeam.Git.GitRepository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Traily.AgentTeam.Git.GitRepository", b =>
                {
                    b.HasOne("Traily.AgentTeam.Git.ManagedProject", "Project")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Traily.AgentTeam.Git.ManagedProject", b =>
                {
                    b.HasOne("Traily.AgentTeam.WorkSources.WorkSourceConnection", "WorkSourceConnection")
                        .WithMany()
                        .HasForeignKey("WorkSourceConnectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkSourceConnection");
                });

            modelBuilder.Entity("Traily.AgentTeam.Integrations.YouTrack.YouTrackConnectionConfiguration", b =>
                {
                    b.HasOne("Traily.AgentTeam.WorkSources.WorkSourceConnection", null)
                        .WithOne()
                        .HasForeignKey("Traily.AgentTeam.Integrations.YouTrack.YouTrackConnectionConfiguration", "ConnectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Traily.AgentTeam.Integrations.YouTrack.YouTrackProjectConfiguration", b =>
                {
                    b.HasOne("Traily.AgentTeam.Git.ManagedProject", null)
                        .WithOne()
                        .HasForeignKey("Traily.AgentTeam.Integrations.YouTrack.YouTrackProjectConfiguration", "SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Traily.AgentTeam.WorkItems.WorkItemExecutionAttempt", b =>
                {
                    b.HasOne("Traily.AgentTeam.WorkItems.WorkItemJob", "Job")
                        .WithMany()
                        .HasForeignKey("WorkItemJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Traily.AgentTeam.WorkItems.WorkItemJob", b =>
                {
                    b.HasOne("Traily.AgentTeam.Agents.AgentProfile", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("Traily.AgentTeam.Agents.AgentProfile", b =>
                {
                    b.Navigation("ExternalIdentities");

                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
